copyright: Oliver Salzburg
dev_addr: 0.0.0.0:8000
docs_dir: docs
edit_uri: /oliversalzburg/plantdb/edit/main/packages/documentation/docs/
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/oliversalzburg/
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
      permalink: "\ue157"
plugins:
  - search
repo_name: oliversalzburg/plantdb
repo_url: https://github.com/oliversalzburg/plantdb/
site_name: PlantDB
site_url: https://plantdb.net/docs/en-US/
theme:
  favicon: assets/images/favicon.ico
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    logo: material/flower
    repo: fontawesome/brands/github
  language: en
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: teal
      primary: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: light green
      primary: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
