name: Documentation Deploy

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Select NodeJS version
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn install

      - name: Build documentation
        run: |
          # Copy stupid shoelace dependencies
          mkdir --parents packages/plant-playground/public/assets/icons
          cp --recursive node_modules/@shoelace-style/shoelace/dist/assets/icons \
            packages/plant-playground/public/assets/icons

          # Build projects & documentation
          yarn workspace @plantdb/libplantdb build
          yarn workspace @plantdb/plant-playground build --base=/plantdb/playground/
          yarn workspace @plantdb/libplantdb docs
          yarn docs:build

          # Put playground and docs on same deployment behind landing-page
          mkdir /tmp/plant-deploy
          cp packages/landing-page/index.html /tmp/plant-deploy/
          cp --recursive packages/documentation/public \
            /tmp/plant-deploy/docs
          cp --recursive packages/plant-playground/output \
            /tmp/plant-deploy/playground

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: /tmp/plant-deploy
          force: true
