name: Documentation Deploy

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Select NodeJS version
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn install

      - name: Build documentation
        run: |
          yarn workspace @plantdb/libplantdb build
          yarn workspace @plantdb/plant-playground build
          yarn docs:build
          cp --recursive packages/plant-playground/output \
            packages/documentation/docs/playground

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4.3.2
        with:
          branch: gh-pages
          folder: packages/documentation/public
